### ISSUE TITLE
Mipmap-Levels stops working after adding mod.

### ISSUE THREAD

**Issue by Gbergz** [Ladysnake/Illuminations#12]
Title^

It's been bugging me for awhile, i thought it was Fabric at first but after disabling 1 mod by 1 in the modpack "All of Fabric v2.3.0" and seeing if the problem goes away. It did when i disabled this mod, Illuminations. Is this fixable? Can't stand playing without mipmap levels on.

Mod version of Illuminations: illuminations-0.1.6-1.14.1.jar
Fabric API version: fabric-api-0.3.0-pre+build.157a.jar

**Comment by doctor4t** [comment]
This is a known bug. One of my images is only 1 by 2px, so that breaks stuff. I was procrastinating to remove it, but I'll do it right now.
