### ISSUE TITLE
Mod Menu

### ISSUE THREAD

**Issue by TheDracoRage** [Ladysnake/Illuminations#137]
Configuration with Mod Menu no longer pops up

**Comment by C47UMX** [comment]
Experiencing the same thing. I assume Effective was ported the same way as it doesnt appear on that too

**Comment by C47UMX** [comment]
you need the "cloth config API" for it to work https://www.curseforge.com/minecraft/mc-mods/cloth-config

**Comment by gardarlogiaevarsson** [comment]
i did that and it still dosnt work for me

**Comment by zulu9** [comment]
> i did that and it still dosnt work for me

Same here.

**Comment by gardarlogiaevarsson** [comment]
> > i did that and it still dosnt work for me
> 
> Same here.

you can also just go through the Minecraft folders to customize it like im doing

**Comment by zulu9** [comment]
I put everything to MEDIUM but it seems only the fireflies actually appear. But I just could test for a few minutes yet. Maybe I just didn't see any of the others yet.

**Comment by doctor4t** [comment]
Planning to move to Midnightlib, in the meantime I've disabled the integration to gain time
