### ISSUE TITLE
No customization

### ISSUE THREAD

**Issue by JulianJake1** [Ladysnake/Illuminations#140]
The customization tab will not show up even tho i have mod menu

**Comment by C47UMX** [comment]
you need the "cloth config API" for it to work

**Comment by C47UMX** [comment]
https://www.curseforge.com/minecraft/mc-mods/cloth-config

**Comment by zulu9** [comment]
Doesn't work even with cloth-config installed here. Other mods that use cloth work fine.

**Comment by doctor4t** [comment]
Planning to move to Midnightlib, in the meantime I've disabled the integration to gain time
