### ISSUE TITLE
[Meta] Licensing

### ISSUE THREAD

**Issue by Thanos1716** [Ladysnake/Illuminations#159]
Hi, I just thought I would bring up the licenses, and merging with Effective. Seeing as Effective is All Rights Reserved and Illuminations is GPL (code at least), does this mean that Effective is going to be re-licensed under the GPL, since I'm pretty sure that's a requirement as part of derivative works of Illuminations, or am I missing something? 
I am not a lawyer, so I don't have a perfect understanding of the legal requirements, but any information would be helpful :)

**Comment by doctor4t** [comment]
It's an oversight that the license for illuminations hasn't been changed, as I recently passed all my mods to full ARR.

In any case Effective will stay ARR given the code for Illuminations is initially mine to license.

**Comment by Thanos1716** [comment]
Hmm I don't think you can do that, but okay, that's unfortunate

**Comment by doctor4t** [comment]
I can, given most of the code will be rewritten anyway, and the assets are already ARR.

I don't see how that's unfortunate given I've always been very accessible for people who want to use my code and assets. This is just a measure against people porting my mods to Forge without my consent.

**Comment by Thanos1716** [comment]
Fair enough, I get why you're doing it, I've just had ARR trauma I guess lol, and with a rewrite then yea I suppose you can
What's wrong with porting to Forge though?

**Comment by doctor4t** [comment]
I do not wish to support a mod loader where the devs caused personal
trouble and trauma to some of my friends and myself.
