### ISSUE TITLE
This mod acts strangely around vanillafix on 1.12.2

### ISSUE THREAD

**Issue by Sunconure11** [Ladysnake/Illuminations#25]
https://pastebin.com/EGWFM5sZ

I'm aware you're not on 1.12.2 anymore, but while trying to track down why my own mod is having issues on a server, I saw this in the logs.

**Comment by Sunconure11** [comment]
https://pastebin.com/9ZySauz9

Found a really WTF crash too.

**Comment by doctor4t** [comment]
Thanks for the report, but 1.12 is very outdated, and I'm not working on Forge anymore.
