### ISSUE TITLE
[Request] Allow Firely/Lightning Bug Spawn in Caves

### ISSUE THREAD

**Issue by scottosx** [Ladysnake/Illuminations#4]
Currently you are limiting to sea level, daytime, and seesky. Can you make variants that overrides these properties, thus allowing underground spawning.

Or a new mob, glowworms like the amazing creatures in this video:

https://www.youtube.com/watch?v=JC41M7RPSec

**Comment by RiverLeviathan** [comment]
I love glowworms, and that's something I wanted to add, but didn't mention, so yes, it will be implemented.
