### ISSUE TITLE
Donator death may cause other server members using Illuminations to crash

### ISSUE THREAD

**Issue by doctor4t** [Ladysnake/Illuminations#41]

**Comment by Leeo97one** [comment]
Mmmh, I think it is still an issue because my friend keeps crashing when I die and sometimes when I teleport to him.

[crash-2020-10-28_00.39.11-client.txt](https://github.com/Ladysnake/Illuminations/files/5459979/crash-2020-10-28_00.39.11-client.txt)

**Comment by doctor4t** [comment]
Should be fixed in the new patch I'll upload right now. If you still have problems, don't hesitate to reopen this issue. Thanks a lot for the heads up!

**Comment by Leeo97one** [comment]
Mmmh unfortunately the issue doesn't seem to be fixed :-/
Here are two more crash reports: https://paste.ee/p/GfTNv & https://paste.ee/p/jdrm1

**Comment by doctor4t** [comment]
Yep, I found a new way to test this thoroughly. Will be fixed in the next patch for real this time. Once again, thanks for the heads up. I'm very sorry!
