### ISSUE TITLE
[Bug Report?] "Eyes in the Dark" are excessive in Nether and End, seem kind of buggy too - Intended?

### ISSUE THREAD

**Issue by Abbanon** [Ladysnake/Illuminations#48]
The Halloween update's "Eyes in the Dark" addition seems to be a bit buggy, because they show up *all over the place* in the Nether and End, and seem to be a bit out of place due to the dimension lighting. Is this intended behaviour?
![2020-10-16_08 27 04](https://user-images.githubusercontent.com/37251822/96304744-a1f60f00-0fca-11eb-981d-2f5a6641e0ba.png)
![2020-10-16_08 26 17](https://user-images.githubusercontent.com/37251822/96304747-a4586900-0fca-11eb-8f91-d1a83c6709fa.png)
![2020-10-16_08 22 18](https://user-images.githubusercontent.com/37251822/96304749-a6222c80-0fca-11eb-9be7-e865d39625e8.png)

**Comment by doctor4t** [comment]
Looks good I don't know what you're even talking about. You're just really popular, all eyes are on you.
