### ISSUE TITLE
Severe Lag in Twilight Forest with Lumen

### ISSUE THREAD

**Issue by st753m** [Ladysnake/Illuminations#5]
Minecraft: 1.12.2
Lumen: 0.4.0
Twilight Forest: 3.7.424

I was having serious lag in the twilight forest, lowering the fps to 1.  I checked with the Lag Goggles mod, and it said the fireflies from Lumen were causing most of the problem.  When I removed Lumen, Twilight Forest began working at the same FPS as the overworld.

**Comment by RiverLeviathan** [comment]
Yeah sorry about that. Fireflies do spawn in mass, and their spawning behavior still needs to be adjusted. Will be corrected in the next update, sorry about that.

**Comment by RiverLeviathan** [comment]
Fixed with the new spawns in the Fabric port.
