### ISSUE TITLE
Lumen on servers?

### ISSUE THREAD

**Issue by ZyionVolkia** [Ladysnake/Illuminations#50]
Heyo, Running a server with lumen installed. it doesnt seem to work when I use the flint to summon my own buddy, I just get errors spammed to the console 
http://prntscr.com/v9oh5r

**Comment by doctor4t** [comment]
Lumen is terribly outdated and no longer supported. Since I don't mod outdated versions and I don't code on Forge anymore, this won't be fixed, sorry.
