### ISSUE TITLE
[1.12.2] Embers spawn in massive quantities, dragging the TPS down massively

### ISSUE THREAD

**Issue by aaronhowser1** [Ladysnake/Illuminations#51]
1.12, sorry

FTBTeam/FTB-University/issues/145

![](https://cdn.discordapp.com/attachments/166630061217153024/773086353277059072/unknown.png)
![](https://cdn.discordapp.com/attachments/166630061217153024/773086507396628500/unknown.png)
![](https://cdn.discordapp.com/attachments/166630061217153024/773086586380353556/unknown.png)

This is using `lumen-Beta 0.4.1.jar`. 
[latest.log](https://github.com/Ladysnake/Illuminations/files/5479782/latest.log)

**Comment by doctor4t** [comment]
Lumen is terribly outdated and no longer supported. Since I don't mod outdated versions and I don't code on Forge anymore, this won't be fixed, sorry.

**Comment by aaronhowser1** [comment]
Totally understandable, thought it was worth a shot. When I get around to 1.16+ pack dev, I'll be sure to give Illuminations a go :)

**Comment by doctor4t** [comment]
You definitely should! Fabric allows me to make a much better mod in every single aspect of it: performance is infinitely better, spawn rates and repartition are consistent, client-sidedness allows to use it on Vanilla servers, etc... When you finally get around to trying Illuminations out, I hope you enjoy it!
