### ISSUE TITLE
"server closed" when opening single player world

### ISSUE THREAD

**Issue by greensad** [Ladysnake/Illuminations#53]
Minecraft 1.16.4, latest fabric api + fabric version, Illuminations 1.2.3
Seems to start a server in the process of launching the single player world, problem doesn't persist when Illuminations is removed.

[crash-2020-11-06_12.26.49-server.txt](https://github.com/Ladysnake/Illuminations/files/5502641/crash-2020-11-06_12.26.49-server.txt)

**Comment by Pyrofab** [comment]
Looks like this crash also affects every dedicated server...
