### ISSUE TITLE
Resourcepacks cant change the texure of particles

### ISSUE THREAD

**Issue by RyanCR03** [Ladysnake/Illuminations#57]
i have a resourcepack that makes it so the textures don't look right with the particles so I decided to change the textures with a resourcepack but no matter how hard I try it doesn't work. is this intended?

**Comment by doctor4t** [comment]
Nope, definetely not. Try and maybe send that resource pack, so I could try it myself and see whether or not it's something on your side or mine.

**Comment by RyanCR03** [comment]
nvm, it fixed itself after i edited pack.mcmeta

**Comment by Pyrofab** [comment]
Could you maybe detail the fix, for future reference ?
