### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Ergo4** [Ladysnake/Illuminations#58]
Bugballs are not harvestable by a hopper. If this was possible one could automatically fill areas where they want fireflies to be where they don't usually spawn. For example, if a build is in an ocean biome. Having them harvestable by a hopper would make the process completely automatic.

**Comment by doctor4t** [comment]
Bugballs have been removed from the mod as of 1.2.4, so this won't be worked on.

However, I am working on more configurability as well as an API that will allow players to easily make their own type of fireflies / illuminations, so there is still a possibility of accomplishing what you wish to in the future.
