### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by RaoqTheWiz** [Ladysnake/Illuminations#60]
Make an aura like in SW: 
https://image-glb.qpyou.cn/hubweb/contents/%EB%87%8C%EC%A0%9C_%EC%A1%B0%ED%95%A9%EC%8B%9D_%EB%B6%88_%EA%B0%81%EC%84%B1%ED%98%95_800_1540450739.png
Looks like this but goes around your MC character.

**Comment by doctor4t** [comment]
Sorry, I don't think I could make it look good.
