### ISSUE TITLE
Art license?

### ISSUE THREAD

**Issue by Dev380** [Ladysnake/Illuminations#66]
Just a suggestion, if possible update art license to something in https://creativecommons.org/share-your-work/public-domain/freeworks/ if you don't want to that's also fine.

**Comment by doctor4t** [comment]
Even though my art is not the best, I prefer keeping total control over it and what people do with it, and this is exactly what ARR allows me to do. I'm not against people remixing or reusing my art, but I prefer they ask beforehand. Doing so has proven the better choice in a few situations in the past, so I'd like to keep it for the time being at least.

As I am still very active and reachable, I don't think ARR is a problem as all the people who've asked me so far received a positive response. So as I said, for the time being, I'd rather keep it the way it is.
