### ISSUE TITLE
[Feature] Add more pride flags in addition to the Trans & Gay flags.

### ISSUE THREAD

**Issue by solonovamax** [Ladysnake/Illuminations#75]

**Comment by solonovamax** [comment]
fuck, forgot to do the description lmao

give me a minute

**Comment by SekoiaTree** [comment]
you're late :)
this has already been done very recently

**Comment by SekoiaTree** [comment]
check the textures

**Comment by solonovamax** [comment]
gg moment lol

**Comment by solonovamax** [comment]
I noticed you're missing a few pride flags, but I'm gonna make a specific issue for them instead of changing this one

**Comment by SekoiaTree** [comment]
yep, thanks :)
