### ISSUE TITLE
Automatic Update is Causing the CTE Harmony pack to crash upon restart. [BUG]

### ISSUE THREAD

**Issue by Darkest-Traveler** [Ladysnake/Illuminations#85]
The Illuminations automatic-update is making my game crash.

Fresh instance of CTE Harmony on GD launcher, Auto-update tells me to restart, restart causes game unable to start up. 

Here is the crash report.
https://pastebin.com/NHhjJLgt

**Comment by doctor4t** [comment]
That's not really because of the auto update... If you had installed it manually, you'd have the same issue. You need a more recent version of Java.

**Comment by doctor4t** [comment]
Update: I wrongly tagged the update on CurseForge, as 1.16.5 instead of 1.17, which is why the auto-updater downloaded Illuminations for 1.17 on your 1.16.5 game, which requires a more recent Java version just like Minecraft 1.17.

My fault, sorry for the mess
