### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by Fourmisain** [Ladysnake/Illuminations#87]
A picture says more than a thousand words:
![thatsalotofdamage](https://user-images.githubusercontent.com/8464472/125174132-6c7dfb00-e1c3-11eb-916e-6f6d6515e34b.png)
This goes on for over 8 pages, therefore I conclude that there are at least 8000 words being said.

**Comment by Fourmisain** [comment]
Jokes aside, you should probably make
https://github.com/Ladysnake/Illuminations/blob/b2bfe338beda8b96cbf1311902f38cf7a9a82d6d/src/main/java/ladysnake/illuminations/client/IlluminationsClient.java#L332
use debug level (enable it in your log4j2.xml config) and also save the string concatenation:
`logger.debug("Retrieved data: {}", playerData);`

**Comment by doctor4t** [comment]
Uh oh, I literally just added a quick log cause breakpoints would mess what I was trying to do, and forgot to remove it, as per usual haha... Thanks for pointing it out, it'll be removed next patch.

**Comment by doctor4t** [comment]
Fixed in 1.6
