### ISSUE TITLE
Too late now, but consider taking screenshots of Illuminations with Canvas Renderer, as that is one of the key points of this mod.

### ISSUE THREAD

**Issue by mj559940** [Ladysnake/Illuminations#89]
Too late now, but consider taking screenshots of Illuminations with Canvas Renderer, as that is one of the key points of this mod.

_Originally posted by @doctor4t in https://github.com/Ladysnake/Illuminations/pull/83#discussion_r659559731_

**Comment by Xiribidus** [comment]
The screenshots featured in the wiki as well as those on the Curseforge page already show the mod combined with Canvas, therefore I am not sure what you are trying to suggest?
