### ISSUE TITLE
Mod doesn't respect config

### ISSUE THREAD

**Issue by Graywaren** [Ladysnake/Illuminations#9]
I tried to disable Faeries and Willothewisps via the config file by setting them to false, but I am still seeing them generate in worlds. I have 1.12.2 and the 0.4.1 lumen and forge b2805. I have other mods, including biomes o plenty, but I'm not sure what would be causing this to ignore the config file. There's no crash log or anything in the launch log about it.

**Comment by doctor4t** [comment]
This must be an incompatibility with some other mod, since I make sure they work every time I publish a new update. Also, sorry, but since development and support has stopped for the 1.12 version, I won't investigate this issue further.
